name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: ./vendor
        key: ${{ runner.os }}-php-${{ hashFiles('composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest
    
    - name: Run test suite for address-book
      run: |
        php ./bin/phpunit

    - name: Init database for heroku
      run: |
        php ./heroku_prepare.php

    - name: Deploy to heroku
      uses: akhileshns/heroku-deploy@v3.6.8
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: symf-address
          heroku_email: "sapraku@ultrahostghana.com"    